import { createElement } from 'lwc';
import Lwc_eg3_greaternumber from 'c/lwc_eg3_greaternumber';

describe('c-lwc-eg3-greaternumber', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-eg3-greaternumber', {
            is: Lwc_eg3_greaternumber
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});